// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveArticleViewsBeforeDate = `-- name: ArchiveArticleViewsBeforeDate :exec
with moved as (
  delete from article_view_daily
  where article_view_daily.view_date < $1
  returning article_view_daily.article_id, article_view_daily.view_date, article_view_daily.views
)
insert into article_view_history (article_id, view_date, views)
select moved.article_id, moved.view_date, moved.views
from moved
on conflict (article_id, view_date)
do update set
  views = article_view_history.views + excluded.views,
  archived_at = now()
`

func (q *Queries) ArchiveArticleViewsBeforeDate(ctx context.Context, viewDate pgtype.Date) error {
	_, err := q.db.Exec(ctx, archiveArticleViewsBeforeDate, viewDate)
	return err
}

const archiveSiteViewsBeforeDate = `-- name: ArchiveSiteViewsBeforeDate :exec
with moved as (
  delete from site_view_daily
  where site_view_daily.view_date < $1
  returning site_view_daily.view_date, site_view_daily.views
)
insert into site_view_history (view_date, views)
select moved.view_date, moved.views
from moved
on conflict (view_date)
do update set
  views = site_view_history.views + excluded.views,
  archived_at = now()
`

func (q *Queries) ArchiveSiteViewsBeforeDate(ctx context.Context, viewDate pgtype.Date) error {
	_, err := q.db.Exec(ctx, archiveSiteViewsBeforeDate, viewDate)
	return err
}

const getTodaySiteViews = `-- name: GetTodaySiteViews :one
select coalesce(views, 0)::int as views
from site_view_daily
where view_date = current_date
`

func (q *Queries) GetTodaySiteViews(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getTodaySiteViews)
	var views int32
	err := row.Scan(&views)
	return views, err
}

const listArticleAnalyticsRows = `-- name: ListArticleAnalyticsRows :many
with period_views as (
  select article_id, sum(views)::int as views
  from (
    select article_id, views
    from article_view_history
    where view_date >= current_date - (($1::int - 1) * interval '1 day')
      and view_date < current_date
    union all
    select article_id, views
    from article_view_daily
    where view_date >= current_date - (($1::int - 1) * interval '1 day')
  ) combined
  group by article_id
), today_views as (
  select article_id, sum(views)::int as views
  from article_view_daily
  where view_date = current_date
  group by article_id
), total_views as (
  select article_id, sum(views)::int as views
  from (
    select article_id, views
    from article_view_history
    union all
    select article_id, views
    from article_view_daily
  ) combined
  group by article_id
)
select
  a.slug,
  a.title,
  coalesce(today_views.views, 0)::int as today_views,
  coalesce(period_views.views, 0)::int as period_views,
  coalesce(total_views.views, 0)::int as total_views,
  a.published_at
from articles a
left join today_views on today_views.article_id = a.article_id
left join period_views on period_views.article_id = a.article_id
left join total_views on total_views.article_id = a.article_id
where a.status = 'published'
order by period_views desc, today_views desc, a.published_at desc nulls last
`

type ListArticleAnalyticsRowsRow struct {
	Slug        string
	Title       string
	TodayViews  int32
	PeriodViews int32
	TotalViews  int32
	PublishedAt pgtype.Timestamptz
}

func (q *Queries) ListArticleAnalyticsRows(ctx context.Context, dollar_1 int32) ([]ListArticleAnalyticsRowsRow, error) {
	rows, err := q.db.Query(ctx, listArticleAnalyticsRows, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArticleAnalyticsRowsRow
	for rows.Next() {
		var i ListArticleAnalyticsRowsRow
		if err := rows.Scan(
			&i.Slug,
			&i.Title,
			&i.TodayViews,
			&i.PeriodViews,
			&i.TotalViews,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHotArticles = `-- name: ListHotArticles :many
with article_views as (
  select article_id, sum(views)::int as views
  from (
    select article_id, views
    from article_view_history
    where view_date >= current_date - interval '6 days'
      and view_date < current_date
    union all
    select article_id, views
    from article_view_daily
    where view_date >= current_date - interval '6 days'
  ) combined
  group by article_id
)
select
  a.article_id,
  a.slug,
  a.title,
  coalesce(v.views, 0)::int as views
from articles a
left join article_views v on v.article_id = a.article_id
where a.status = 'published'
order by views desc, a.published_at desc nulls last
limit $1
`

type ListHotArticlesRow struct {
	ArticleID pgtype.UUID
	Slug      string
	Title     string
	Views     int32
}

func (q *Queries) ListHotArticles(ctx context.Context, limit int32) ([]ListHotArticlesRow, error) {
	rows, err := q.db.Query(ctx, listHotArticles, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHotArticlesRow
	for rows.Next() {
		var i ListHotArticlesRow
		if err := rows.Scan(
			&i.ArticleID,
			&i.Slug,
			&i.Title,
			&i.Views,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiteViewsLast7Days = `-- name: ListSiteViewsLast7Days :many
with days as (
  select generate_series(current_date - interval '6 days', current_date, interval '1 day')::date as view_date
), views as (
  select view_date, sum(views)::int as views
  from (
    select view_date, views
    from site_view_history
    where view_date >= current_date - interval '6 days'
      and view_date < current_date
    union all
    select view_date, views
    from site_view_daily
    where view_date >= current_date - interval '6 days'
  ) combined
  group by view_date
)
select days.view_date, coalesce(views.views, 0)::int as views
from days
left join views on views.view_date = days.view_date
order by days.view_date asc
`

type ListSiteViewsLast7DaysRow struct {
	ViewDate pgtype.Date
	Views    int32
}

func (q *Queries) ListSiteViewsLast7Days(ctx context.Context) ([]ListSiteViewsLast7DaysRow, error) {
	rows, err := q.db.Query(ctx, listSiteViewsLast7Days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSiteViewsLast7DaysRow
	for rows.Next() {
		var i ListSiteViewsLast7DaysRow
		if err := rows.Scan(&i.ViewDate, &i.Views); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertArticleViewDaily = `-- name: UpsertArticleViewDaily :exec
insert into article_view_daily (article_id, view_date, views)
values ($1, $2, $3)
on conflict (article_id, view_date)
do update set views = article_view_daily.views + excluded.views
`

type UpsertArticleViewDailyParams struct {
	ArticleID pgtype.UUID
	ViewDate  pgtype.Date
	Views     int32
}

func (q *Queries) UpsertArticleViewDaily(ctx context.Context, arg UpsertArticleViewDailyParams) error {
	_, err := q.db.Exec(ctx, upsertArticleViewDaily, arg.ArticleID, arg.ViewDate, arg.Views)
	return err
}

const upsertSiteViewDaily = `-- name: UpsertSiteViewDaily :exec
insert into site_view_daily (view_date, views)
values ($1, $2)
on conflict (view_date)
do update set views = site_view_daily.views + excluded.views
`

type UpsertSiteViewDailyParams struct {
	ViewDate pgtype.Date
	Views    int32
}

func (q *Queries) UpsertSiteViewDaily(ctx context.Context, arg UpsertSiteViewDailyParams) error {
	_, err := q.db.Exec(ctx, upsertSiteViewDaily, arg.ViewDate, arg.Views)
	return err
}
