// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertArticleViewDaily = `-- name: UpsertArticleViewDaily :exec
insert into article_view_daily (article_id, view_date, views)
values ($1, $2, $3)
on conflict (article_id, view_date)
do update set views = article_view_daily.views + excluded.views
`

type UpsertArticleViewDailyParams struct {
	ArticleID pgtype.UUID
	ViewDate  pgtype.Date
	Views     int32
}

func (q *Queries) UpsertArticleViewDaily(ctx context.Context, arg UpsertArticleViewDailyParams) error {
	_, err := q.db.Exec(ctx, upsertArticleViewDaily, arg.ArticleID, arg.ViewDate, arg.Views)
	return err
}

const upsertSiteViewDaily = `-- name: UpsertSiteViewDaily :exec
insert into site_view_daily (view_date, views)
values ($1, $2)
on conflict (view_date)
do update set views = site_view_daily.views + excluded.views
`

type UpsertSiteViewDailyParams struct {
	ViewDate pgtype.Date
	Views    int32
}

func (q *Queries) UpsertSiteViewDaily(ctx context.Context, arg UpsertSiteViewDailyParams) error {
	_, err := q.db.Exec(ctx, upsertSiteViewDaily, arg.ViewDate, arg.Views)
	return err
}
