// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics_events.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAnalyticsEvent = `-- name: CreateAnalyticsEvent :one
insert into analytics_events (
  article_id,
  event_type,
  ip_hash,
  user_agent
) values (
  $1,
  $2,
  $3,
  $4
)
returning event_id, article_id, event_type, ip_hash, user_agent, created_at
`

type CreateAnalyticsEventParams struct {
	ArticleID pgtype.UUID
	EventType string
	IpHash    string
	UserAgent pgtype.Text
}

type CreateAnalyticsEventRow struct {
	EventID   pgtype.UUID
	ArticleID pgtype.UUID
	EventType string
	IpHash    string
	UserAgent pgtype.Text
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateAnalyticsEvent(ctx context.Context, arg CreateAnalyticsEventParams) (CreateAnalyticsEventRow, error) {
	row := q.db.QueryRow(ctx, createAnalyticsEvent,
		arg.ArticleID,
		arg.EventType,
		arg.IpHash,
		arg.UserAgent,
	)
	var i CreateAnalyticsEventRow
	err := row.Scan(
		&i.EventID,
		&i.ArticleID,
		&i.EventType,
		&i.IpHash,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const listArticleViewTrend = `-- name: ListArticleViewTrend :many
select
  combined.view_date,
  a.slug,
  a.title,
  sum(combined.views)::int as views
from (
  select article_id, view_date, views
  from article_view_history
  where view_date >= current_date - (($1::int - 1) * interval '1 day')
    and view_date < current_date
  union all
  select article_id, view_date, views
  from article_view_daily
  where view_date >= current_date - (($1::int - 1) * interval '1 day')
) combined
join articles a on a.article_id = combined.article_id
where a.status = 'published'
group by combined.view_date, a.slug, a.title
order by combined.view_date asc, views desc, a.slug asc
`

type ListArticleViewTrendRow struct {
	ViewDate pgtype.Date
	Slug     string
	Title    string
	Views    int32
}

func (q *Queries) ListArticleViewTrend(ctx context.Context, days int32) ([]ListArticleViewTrendRow, error) {
	rows, err := q.db.Query(ctx, listArticleViewTrend, days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArticleViewTrendRow
	for rows.Next() {
		var i ListArticleViewTrendRow
		if err := rows.Scan(
			&i.ViewDate,
			&i.Slug,
			&i.Title,
			&i.Views,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiteViewTrend = `-- name: ListSiteViewTrend :many
with days as (
  select generate_series(current_date - (($1::int - 1) * interval '1 day'), current_date, interval '1 day')::date as view_date
), views as (
  select view_date, sum(views)::int as views
  from (
    select view_date, views
    from site_view_history
    where view_date >= current_date - (($1::int - 1) * interval '1 day')
      and view_date < current_date
    union all
    select view_date, views
    from site_view_daily
    where view_date >= current_date - (($1::int - 1) * interval '1 day')
  ) combined
  group by view_date
)
select days.view_date, coalesce(views.views, 0)::int as views
from days
left join views on views.view_date = days.view_date
order by days.view_date asc
`

type ListSiteViewTrendRow struct {
	ViewDate pgtype.Date
	Views    int32
}

func (q *Queries) ListSiteViewTrend(ctx context.Context, days int32) ([]ListSiteViewTrendRow, error) {
	rows, err := q.db.Query(ctx, listSiteViewTrend, days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSiteViewTrendRow
	for rows.Next() {
		var i ListSiteViewTrendRow
		if err := rows.Scan(&i.ViewDate, &i.Views); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
