// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: articles.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDraftArticle = `-- name: CreateDraftArticle :one
insert into articles (
  slug,
  article_name,
  title,
  summary,
  body_mdx,
  tags,
  featured,
  featured_rank,
  featured_at,
  cover_image_url,
  author_id
) values (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
returning
  article_id,
  slug,
  article_name,
  title,
  summary,
  body_mdx,
  status,
  tags,
  featured,
  featured_rank,
  featured_at,
  cover_image_url,
  published_at,
  author_id,
  created_at,
  updated_at,
  version,
  search_vector
`

type CreateDraftArticleParams struct {
	Slug          string
	ArticleName   string
	Title         string
	Summary       string
	BodyMdx       string
	Tags          []string
	Featured      bool
	FeaturedRank  int32
	FeaturedAt    pgtype.Timestamptz
	CoverImageUrl pgtype.Text
	AuthorID      pgtype.UUID
}

type CreateDraftArticleRow struct {
	ArticleID     pgtype.UUID
	Slug          string
	ArticleName   string
	Title         string
	Summary       string
	BodyMdx       string
	Status        ArticleStatus
	Tags          []string
	Featured      bool
	FeaturedRank  int32
	FeaturedAt    pgtype.Timestamptz
	CoverImageUrl pgtype.Text
	PublishedAt   pgtype.Timestamptz
	AuthorID      pgtype.UUID
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Version       int32
	SearchVector  interface{}
}

func (q *Queries) CreateDraftArticle(ctx context.Context, arg CreateDraftArticleParams) (CreateDraftArticleRow, error) {
	row := q.db.QueryRow(ctx, createDraftArticle,
		arg.Slug,
		arg.ArticleName,
		arg.Title,
		arg.Summary,
		arg.BodyMdx,
		arg.Tags,
		arg.Featured,
		arg.FeaturedRank,
		arg.FeaturedAt,
		arg.CoverImageUrl,
		arg.AuthorID,
	)
	var i CreateDraftArticleRow
	err := row.Scan(
		&i.ArticleID,
		&i.Slug,
		&i.ArticleName,
		&i.Title,
		&i.Summary,
		&i.BodyMdx,
		&i.Status,
		&i.Tags,
		&i.Featured,
		&i.FeaturedRank,
		&i.FeaturedAt,
		&i.CoverImageUrl,
		&i.PublishedAt,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.SearchVector,
	)
	return i, err
}

const getArticleByArticleName = `-- name: GetArticleByArticleName :one
select
  article_id,
  slug,
  article_name,
  title,
  summary,
  body_mdx,
  status,
  tags,
  featured,
  featured_rank,
  featured_at,
  cover_image_url,
  published_at,
  author_id,
  created_at,
  updated_at,
  version,
  search_vector
from articles
where article_name = $1 and status = 'published'
`

type GetArticleByArticleNameRow struct {
	ArticleID     pgtype.UUID
	Slug          string
	ArticleName   string
	Title         string
	Summary       string
	BodyMdx       string
	Status        ArticleStatus
	Tags          []string
	Featured      bool
	FeaturedRank  int32
	FeaturedAt    pgtype.Timestamptz
	CoverImageUrl pgtype.Text
	PublishedAt   pgtype.Timestamptz
	AuthorID      pgtype.UUID
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Version       int32
	SearchVector  interface{}
}

func (q *Queries) GetArticleByArticleName(ctx context.Context, articleName string) (GetArticleByArticleNameRow, error) {
	row := q.db.QueryRow(ctx, getArticleByArticleName, articleName)
	var i GetArticleByArticleNameRow
	err := row.Scan(
		&i.ArticleID,
		&i.Slug,
		&i.ArticleName,
		&i.Title,
		&i.Summary,
		&i.BodyMdx,
		&i.Status,
		&i.Tags,
		&i.Featured,
		&i.FeaturedRank,
		&i.FeaturedAt,
		&i.CoverImageUrl,
		&i.PublishedAt,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.SearchVector,
	)
	return i, err
}

const getArticleByID = `-- name: GetArticleByID :one
select
  article_id,
  slug,
  article_name,
  title,
  summary,
  body_mdx,
  status,
  tags,
  featured,
  featured_rank,
  featured_at,
  cover_image_url,
  published_at,
  author_id,
  created_at,
  updated_at,
  version,
  search_vector
from articles
where article_id = $1
`

type GetArticleByIDRow struct {
	ArticleID     pgtype.UUID
	Slug          string
	ArticleName   string
	Title         string
	Summary       string
	BodyMdx       string
	Status        ArticleStatus
	Tags          []string
	Featured      bool
	FeaturedRank  int32
	FeaturedAt    pgtype.Timestamptz
	CoverImageUrl pgtype.Text
	PublishedAt   pgtype.Timestamptz
	AuthorID      pgtype.UUID
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Version       int32
	SearchVector  interface{}
}

func (q *Queries) GetArticleByID(ctx context.Context, articleID pgtype.UUID) (GetArticleByIDRow, error) {
	row := q.db.QueryRow(ctx, getArticleByID, articleID)
	var i GetArticleByIDRow
	err := row.Scan(
		&i.ArticleID,
		&i.Slug,
		&i.ArticleName,
		&i.Title,
		&i.Summary,
		&i.BodyMdx,
		&i.Status,
		&i.Tags,
		&i.Featured,
		&i.FeaturedRank,
		&i.FeaturedAt,
		&i.CoverImageUrl,
		&i.PublishedAt,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.SearchVector,
	)
	return i, err
}

const getArticleBySlug = `-- name: GetArticleBySlug :one
select
  article_id,
  slug,
  article_name,
  title,
  summary,
  body_mdx,
  status,
  tags,
  featured,
  featured_rank,
  featured_at,
  cover_image_url,
  published_at,
  author_id,
  created_at,
  updated_at,
  version,
  search_vector
from articles
where slug = $1 and status = 'published'
`

type GetArticleBySlugRow struct {
	ArticleID     pgtype.UUID
	Slug          string
	ArticleName   string
	Title         string
	Summary       string
	BodyMdx       string
	Status        ArticleStatus
	Tags          []string
	Featured      bool
	FeaturedRank  int32
	FeaturedAt    pgtype.Timestamptz
	CoverImageUrl pgtype.Text
	PublishedAt   pgtype.Timestamptz
	AuthorID      pgtype.UUID
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Version       int32
	SearchVector  interface{}
}

func (q *Queries) GetArticleBySlug(ctx context.Context, slug string) (GetArticleBySlugRow, error) {
	row := q.db.QueryRow(ctx, getArticleBySlug, slug)
	var i GetArticleBySlugRow
	err := row.Scan(
		&i.ArticleID,
		&i.Slug,
		&i.ArticleName,
		&i.Title,
		&i.Summary,
		&i.BodyMdx,
		&i.Status,
		&i.Tags,
		&i.Featured,
		&i.FeaturedRank,
		&i.FeaturedAt,
		&i.CoverImageUrl,
		&i.PublishedAt,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.SearchVector,
	)
	return i, err
}

const listAdminArticles = `-- name: ListAdminArticles :many
select
  article_id,
  slug,
  article_name,
  title,
  summary,
  body_mdx,
  status,
  tags,
  featured,
  featured_rank,
  featured_at,
  cover_image_url,
  published_at,
  author_id,
  created_at,
  updated_at,
  version,
  search_vector
from articles
order by updated_at desc, created_at desc
`

type ListAdminArticlesRow struct {
	ArticleID     pgtype.UUID
	Slug          string
	ArticleName   string
	Title         string
	Summary       string
	BodyMdx       string
	Status        ArticleStatus
	Tags          []string
	Featured      bool
	FeaturedRank  int32
	FeaturedAt    pgtype.Timestamptz
	CoverImageUrl pgtype.Text
	PublishedAt   pgtype.Timestamptz
	AuthorID      pgtype.UUID
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Version       int32
	SearchVector  interface{}
}

func (q *Queries) ListAdminArticles(ctx context.Context) ([]ListAdminArticlesRow, error) {
	rows, err := q.db.Query(ctx, listAdminArticles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminArticlesRow
	for rows.Next() {
		var i ListAdminArticlesRow
		if err := rows.Scan(
			&i.ArticleID,
			&i.Slug,
			&i.ArticleName,
			&i.Title,
			&i.Summary,
			&i.BodyMdx,
			&i.Status,
			&i.Tags,
			&i.Featured,
			&i.FeaturedRank,
			&i.FeaturedAt,
			&i.CoverImageUrl,
			&i.PublishedAt,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedArticles = `-- name: ListPublishedArticles :many
select
  article_id,
  slug,
  article_name,
  title,
  summary,
  body_mdx,
  status,
  tags,
  featured,
  featured_rank,
  featured_at,
  cover_image_url,
  published_at,
  author_id,
  created_at,
  updated_at,
  version,
  search_vector
from articles
where status = 'published'
order by published_at desc nulls last, created_at desc
`

type ListPublishedArticlesRow struct {
	ArticleID     pgtype.UUID
	Slug          string
	ArticleName   string
	Title         string
	Summary       string
	BodyMdx       string
	Status        ArticleStatus
	Tags          []string
	Featured      bool
	FeaturedRank  int32
	FeaturedAt    pgtype.Timestamptz
	CoverImageUrl pgtype.Text
	PublishedAt   pgtype.Timestamptz
	AuthorID      pgtype.UUID
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Version       int32
	SearchVector  interface{}
}

func (q *Queries) ListPublishedArticles(ctx context.Context) ([]ListPublishedArticlesRow, error) {
	rows, err := q.db.Query(ctx, listPublishedArticles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedArticlesRow
	for rows.Next() {
		var i ListPublishedArticlesRow
		if err := rows.Scan(
			&i.ArticleID,
			&i.Slug,
			&i.ArticleName,
			&i.Title,
			&i.Summary,
			&i.BodyMdx,
			&i.Status,
			&i.Tags,
			&i.Featured,
			&i.FeaturedRank,
			&i.FeaturedAt,
			&i.CoverImageUrl,
			&i.PublishedAt,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishArticle = `-- name: PublishArticle :one
update articles
set
  status = 'published',
  published_at = coalesce(published_at, now()),
  updated_at = now()
where article_id = $1
  and status = 'draft'
returning
  article_id,
  slug,
  article_name,
  title,
  summary,
  body_mdx,
  status,
  tags,
  featured,
  featured_rank,
  featured_at,
  cover_image_url,
  published_at,
  author_id,
  created_at,
  updated_at,
  version,
  search_vector
`

type PublishArticleRow struct {
	ArticleID     pgtype.UUID
	Slug          string
	ArticleName   string
	Title         string
	Summary       string
	BodyMdx       string
	Status        ArticleStatus
	Tags          []string
	Featured      bool
	FeaturedRank  int32
	FeaturedAt    pgtype.Timestamptz
	CoverImageUrl pgtype.Text
	PublishedAt   pgtype.Timestamptz
	AuthorID      pgtype.UUID
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Version       int32
	SearchVector  interface{}
}

func (q *Queries) PublishArticle(ctx context.Context, articleID pgtype.UUID) (PublishArticleRow, error) {
	row := q.db.QueryRow(ctx, publishArticle, articleID)
	var i PublishArticleRow
	err := row.Scan(
		&i.ArticleID,
		&i.Slug,
		&i.ArticleName,
		&i.Title,
		&i.Summary,
		&i.BodyMdx,
		&i.Status,
		&i.Tags,
		&i.Featured,
		&i.FeaturedRank,
		&i.FeaturedAt,
		&i.CoverImageUrl,
		&i.PublishedAt,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.SearchVector,
	)
	return i, err
}

const updateDraftArticle = `-- name: UpdateDraftArticle :one
update articles
set
  slug = $2,
  article_name = $3,
  title = $4,
  summary = $5,
  body_mdx = $6,
  tags = $7,
  featured = $8,
  featured_rank = $9,
  featured_at = $10,
  cover_image_url = $11,
  updated_at = now()
where article_id = $1
returning
  article_id,
  slug,
  article_name,
  title,
  summary,
  body_mdx,
  status,
  tags,
  featured,
  featured_rank,
  featured_at,
  cover_image_url,
  published_at,
  author_id,
  created_at,
  updated_at,
  version,
  search_vector
`

type UpdateDraftArticleParams struct {
	ArticleID     pgtype.UUID
	Slug          string
	ArticleName   string
	Title         string
	Summary       string
	BodyMdx       string
	Tags          []string
	Featured      bool
	FeaturedRank  int32
	FeaturedAt    pgtype.Timestamptz
	CoverImageUrl pgtype.Text
}

type UpdateDraftArticleRow struct {
	ArticleID     pgtype.UUID
	Slug          string
	ArticleName   string
	Title         string
	Summary       string
	BodyMdx       string
	Status        ArticleStatus
	Tags          []string
	Featured      bool
	FeaturedRank  int32
	FeaturedAt    pgtype.Timestamptz
	CoverImageUrl pgtype.Text
	PublishedAt   pgtype.Timestamptz
	AuthorID      pgtype.UUID
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Version       int32
	SearchVector  interface{}
}

func (q *Queries) UpdateDraftArticle(ctx context.Context, arg UpdateDraftArticleParams) (UpdateDraftArticleRow, error) {
	row := q.db.QueryRow(ctx, updateDraftArticle,
		arg.ArticleID,
		arg.Slug,
		arg.ArticleName,
		arg.Title,
		arg.Summary,
		arg.BodyMdx,
		arg.Tags,
		arg.Featured,
		arg.FeaturedRank,
		arg.FeaturedAt,
		arg.CoverImageUrl,
	)
	var i UpdateDraftArticleRow
	err := row.Scan(
		&i.ArticleID,
		&i.Slug,
		&i.ArticleName,
		&i.Title,
		&i.Summary,
		&i.BodyMdx,
		&i.Status,
		&i.Tags,
		&i.Featured,
		&i.FeaturedRank,
		&i.FeaturedAt,
		&i.CoverImageUrl,
		&i.PublishedAt,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.SearchVector,
	)
	return i, err
}

const upsertPublishedArticleFromImport = `-- name: UpsertPublishedArticleFromImport :one
insert into articles (
  slug,
  article_name,
  title,
  summary,
  body_mdx,
  status,
  tags,
  featured,
  featured_rank,
  featured_at,
  cover_image_url,
  published_at,
  author_id
) values (
  $1, $2, $3, $4, $5, 'published', $6, $7, $8, $9, $10, $11, $12
)
on conflict (slug)
do update set
  article_name = excluded.article_name,
  title = excluded.title,
  summary = excluded.summary,
  body_mdx = excluded.body_mdx,
  status = 'published',
  tags = excluded.tags,
  featured = excluded.featured,
  featured_rank = excluded.featured_rank,
  featured_at = excluded.featured_at,
  cover_image_url = excluded.cover_image_url,
  published_at = excluded.published_at,
  author_id = excluded.author_id,
  updated_at = now()
returning
  article_id,
  slug,
  article_name,
  title,
  summary,
  body_mdx,
  status,
  tags,
  featured,
  featured_rank,
  featured_at,
  cover_image_url,
  published_at,
  author_id,
  created_at,
  updated_at,
  version,
  search_vector
`

type UpsertPublishedArticleFromImportParams struct {
	Slug          string
	ArticleName   string
	Title         string
	Summary       string
	BodyMdx       string
	Tags          []string
	Featured      bool
	FeaturedRank  int32
	FeaturedAt    pgtype.Timestamptz
	CoverImageUrl pgtype.Text
	PublishedAt   pgtype.Timestamptz
	AuthorID      pgtype.UUID
}

type UpsertPublishedArticleFromImportRow struct {
	ArticleID     pgtype.UUID
	Slug          string
	ArticleName   string
	Title         string
	Summary       string
	BodyMdx       string
	Status        ArticleStatus
	Tags          []string
	Featured      bool
	FeaturedRank  int32
	FeaturedAt    pgtype.Timestamptz
	CoverImageUrl pgtype.Text
	PublishedAt   pgtype.Timestamptz
	AuthorID      pgtype.UUID
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Version       int32
	SearchVector  interface{}
}

func (q *Queries) UpsertPublishedArticleFromImport(ctx context.Context, arg UpsertPublishedArticleFromImportParams) (UpsertPublishedArticleFromImportRow, error) {
	row := q.db.QueryRow(ctx, upsertPublishedArticleFromImport,
		arg.Slug,
		arg.ArticleName,
		arg.Title,
		arg.Summary,
		arg.BodyMdx,
		arg.Tags,
		arg.Featured,
		arg.FeaturedRank,
		arg.FeaturedAt,
		arg.CoverImageUrl,
		arg.PublishedAt,
		arg.AuthorID,
	)
	var i UpsertPublishedArticleFromImportRow
	err := row.Scan(
		&i.ArticleID,
		&i.Slug,
		&i.ArticleName,
		&i.Title,
		&i.Summary,
		&i.BodyMdx,
		&i.Status,
		&i.Tags,
		&i.Featured,
		&i.FeaturedRank,
		&i.FeaturedAt,
		&i.CoverImageUrl,
		&i.PublishedAt,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.SearchVector,
	)
	return i, err
}
