// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: articles.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDraftArticle = `-- name: CreateDraftArticle :one
insert into articles (
  slug,
  title,
  summary,
  body_mdx,
  tags,
  featured,
  cover_image_url,
  author_id
) values (
  $1, $2, $3, $4, $5, $6, $7, $8
)
returning
  article_id,
  slug,
  title,
  summary,
  body_mdx,
  status,
  tags,
  featured,
  cover_image_url,
  published_at,
  author_id,
  created_at,
  updated_at,
  version
`

type CreateDraftArticleParams struct {
	Slug          string
	Title         string
	Summary       string
	BodyMdx       string
	Tags          []string
	Featured      bool
	CoverImageUrl pgtype.Text
	AuthorID      pgtype.UUID
}

func (q *Queries) CreateDraftArticle(ctx context.Context, arg CreateDraftArticleParams) (Article, error) {
	row := q.db.QueryRow(ctx, createDraftArticle,
		arg.Slug,
		arg.Title,
		arg.Summary,
		arg.BodyMdx,
		arg.Tags,
		arg.Featured,
		arg.CoverImageUrl,
		arg.AuthorID,
	)
	var i Article
	err := row.Scan(
		&i.ArticleID,
		&i.Slug,
		&i.Title,
		&i.Summary,
		&i.BodyMdx,
		&i.Status,
		&i.Tags,
		&i.Featured,
		&i.CoverImageUrl,
		&i.PublishedAt,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getArticleByID = `-- name: GetArticleByID :one
select
  article_id,
  slug,
  title,
  summary,
  body_mdx,
  status,
  tags,
  featured,
  cover_image_url,
  published_at,
  author_id,
  created_at,
  updated_at,
  version
from articles
where article_id = $1
`

func (q *Queries) GetArticleByID(ctx context.Context, articleID pgtype.UUID) (Article, error) {
	row := q.db.QueryRow(ctx, getArticleByID, articleID)
	var i Article
	err := row.Scan(
		&i.ArticleID,
		&i.Slug,
		&i.Title,
		&i.Summary,
		&i.BodyMdx,
		&i.Status,
		&i.Tags,
		&i.Featured,
		&i.CoverImageUrl,
		&i.PublishedAt,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getArticleBySlug = `-- name: GetArticleBySlug :one
select
  article_id,
  slug,
  title,
  summary,
  body_mdx,
  status,
  tags,
  featured,
  cover_image_url,
  published_at,
  author_id,
  created_at,
  updated_at,
  version
from articles
where slug = $1 and status = 'published'
`

func (q *Queries) GetArticleBySlug(ctx context.Context, slug string) (Article, error) {
	row := q.db.QueryRow(ctx, getArticleBySlug, slug)
	var i Article
	err := row.Scan(
		&i.ArticleID,
		&i.Slug,
		&i.Title,
		&i.Summary,
		&i.BodyMdx,
		&i.Status,
		&i.Tags,
		&i.Featured,
		&i.CoverImageUrl,
		&i.PublishedAt,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const listAdminArticles = `-- name: ListAdminArticles :many
select
  article_id,
  slug,
  title,
  summary,
  body_mdx,
  status,
  tags,
  featured,
  cover_image_url,
  published_at,
  author_id,
  created_at,
  updated_at,
  version
from articles
order by updated_at desc, created_at desc
`

func (q *Queries) ListAdminArticles(ctx context.Context) ([]Article, error) {
	rows, err := q.db.Query(ctx, listAdminArticles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ArticleID,
			&i.Slug,
			&i.Title,
			&i.Summary,
			&i.BodyMdx,
			&i.Status,
			&i.Tags,
			&i.Featured,
			&i.CoverImageUrl,
			&i.PublishedAt,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedArticles = `-- name: ListPublishedArticles :many
select
  article_id,
  slug,
  title,
  summary,
  body_mdx,
  status,
  tags,
  featured,
  cover_image_url,
  published_at,
  author_id,
  created_at,
  updated_at,
  version
from articles
where status = 'published'
order by published_at desc nulls last, created_at desc
`

func (q *Queries) ListPublishedArticles(ctx context.Context) ([]Article, error) {
	rows, err := q.db.Query(ctx, listPublishedArticles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ArticleID,
			&i.Slug,
			&i.Title,
			&i.Summary,
			&i.BodyMdx,
			&i.Status,
			&i.Tags,
			&i.Featured,
			&i.CoverImageUrl,
			&i.PublishedAt,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishArticle = `-- name: PublishArticle :one
update articles
set
  status = 'published',
  published_at = coalesce(published_at, now()),
  updated_at = now()
where article_id = $1
returning
  article_id,
  slug,
  title,
  summary,
  body_mdx,
  status,
  tags,
  featured,
  cover_image_url,
  published_at,
  author_id,
  created_at,
  updated_at,
  version
`

func (q *Queries) PublishArticle(ctx context.Context, articleID pgtype.UUID) (Article, error) {
	row := q.db.QueryRow(ctx, publishArticle, articleID)
	var i Article
	err := row.Scan(
		&i.ArticleID,
		&i.Slug,
		&i.Title,
		&i.Summary,
		&i.BodyMdx,
		&i.Status,
		&i.Tags,
		&i.Featured,
		&i.CoverImageUrl,
		&i.PublishedAt,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const updateDraftArticle = `-- name: UpdateDraftArticle :one
update articles
set
  slug = $2,
  title = $3,
  summary = $4,
  body_mdx = $5,
  tags = $6,
  featured = $7,
  cover_image_url = $8,
  updated_at = now()
where article_id = $1
returning
  article_id,
  slug,
  title,
  summary,
  body_mdx,
  status,
  tags,
  featured,
  cover_image_url,
  published_at,
  author_id,
  created_at,
  updated_at,
  version
`

type UpdateDraftArticleParams struct {
	ArticleID     pgtype.UUID
	Slug          string
	Title         string
	Summary       string
	BodyMdx       string
	Tags          []string
	Featured      bool
	CoverImageUrl pgtype.Text
}

func (q *Queries) UpdateDraftArticle(ctx context.Context, arg UpdateDraftArticleParams) (Article, error) {
	row := q.db.QueryRow(ctx, updateDraftArticle,
		arg.ArticleID,
		arg.Slug,
		arg.Title,
		arg.Summary,
		arg.BodyMdx,
		arg.Tags,
		arg.Featured,
		arg.CoverImageUrl,
	)
	var i Article
	err := row.Scan(
		&i.ArticleID,
		&i.Slug,
		&i.Title,
		&i.Summary,
		&i.BodyMdx,
		&i.Status,
		&i.Tags,
		&i.Featured,
		&i.CoverImageUrl,
		&i.PublishedAt,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const upsertPublishedArticleFromImport = `-- name: UpsertPublishedArticleFromImport :one
insert into articles (
  slug,
  title,
  summary,
  body_mdx,
  status,
  tags,
  featured,
  cover_image_url,
  published_at,
  author_id
) values (
  $1, $2, $3, $4, 'published', $5, $6, $7, $8, $9
)
on conflict (slug)
do update set
  title = excluded.title,
  summary = excluded.summary,
  body_mdx = excluded.body_mdx,
  status = 'published',
  tags = excluded.tags,
  featured = excluded.featured,
  cover_image_url = excluded.cover_image_url,
  published_at = excluded.published_at,
  author_id = excluded.author_id,
  updated_at = now()
returning
  article_id,
  slug,
  title,
  summary,
  body_mdx,
  status,
  tags,
  featured,
  cover_image_url,
  published_at,
  author_id,
  created_at,
  updated_at,
  version
`

type UpsertPublishedArticleFromImportParams struct {
	Slug          string
	Title         string
	Summary       string
	BodyMdx       string
	Tags          []string
	Featured      bool
	CoverImageUrl pgtype.Text
	PublishedAt   pgtype.Timestamptz
	AuthorID      pgtype.UUID
}

func (q *Queries) UpsertPublishedArticleFromImport(ctx context.Context, arg UpsertPublishedArticleFromImportParams) (Article, error) {
	row := q.db.QueryRow(ctx, upsertPublishedArticleFromImport,
		arg.Slug,
		arg.Title,
		arg.Summary,
		arg.BodyMdx,
		arg.Tags,
		arg.Featured,
		arg.CoverImageUrl,
		arg.PublishedAt,
		arg.AuthorID,
	)
	var i Article
	err := row.Scan(
		&i.ArticleID,
		&i.Slug,
		&i.Title,
		&i.Summary,
		&i.BodyMdx,
		&i.Status,
		&i.Tags,
		&i.Featured,
		&i.CoverImageUrl,
		&i.PublishedAt,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
