// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assets.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAsset = `-- name: CreateAsset :one
insert into assets (
  filename,
  content_type,
  byte_size,
  storage_key,
  public_url,
  created_by
) values (
  $1, $2, $3, $4, $5, $6
)
returning asset_id, filename, content_type, byte_size, storage_key, public_url, created_by, created_at, status, deleted_at
`

type CreateAssetParams struct {
	Filename    string
	ContentType string
	ByteSize    int32
	StorageKey  string
	PublicUrl   pgtype.Text
	CreatedBy   pgtype.UUID
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.Filename,
		arg.ContentType,
		arg.ByteSize,
		arg.StorageKey,
		arg.PublicUrl,
		arg.CreatedBy,
	)
	var i Asset
	err := row.Scan(
		&i.AssetID,
		&i.Filename,
		&i.ContentType,
		&i.ByteSize,
		&i.StorageKey,
		&i.PublicUrl,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Status,
		&i.DeletedAt,
	)
	return i, err
}

const createDownloadEvent = `-- name: CreateDownloadEvent :one
insert into download_events (
  asset_id,
  ip_hash,
  user_agent
) values (
  $1, $2, $3
)
returning event_id, asset_id, ip_hash, user_agent, created_at
`

type CreateDownloadEventParams struct {
	AssetID   pgtype.UUID
	IpHash    string
	UserAgent pgtype.Text
}

func (q *Queries) CreateDownloadEvent(ctx context.Context, arg CreateDownloadEventParams) (DownloadEvent, error) {
	row := q.db.QueryRow(ctx, createDownloadEvent, arg.AssetID, arg.IpHash, arg.UserAgent)
	var i DownloadEvent
	err := row.Scan(
		&i.EventID,
		&i.AssetID,
		&i.IpHash,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const getAssetByID = `-- name: GetAssetByID :one
select asset_id, filename, content_type, byte_size, storage_key, public_url, created_by, created_at, status, deleted_at
from assets
where asset_id = $1
`

func (q *Queries) GetAssetByID(ctx context.Context, assetID pgtype.UUID) (Asset, error) {
	row := q.db.QueryRow(ctx, getAssetByID, assetID)
	var i Asset
	err := row.Scan(
		&i.AssetID,
		&i.Filename,
		&i.ContentType,
		&i.ByteSize,
		&i.StorageKey,
		&i.PublicUrl,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Status,
		&i.DeletedAt,
	)
	return i, err
}

const listAssets = `-- name: ListAssets :many
select asset_id, filename, content_type, byte_size, storage_key, public_url, created_by, created_at, status, deleted_at
from assets
order by created_at desc
`

func (q *Queries) ListAssets(ctx context.Context) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.AssetID,
			&i.Filename,
			&i.ContentType,
			&i.ByteSize,
			&i.StorageKey,
			&i.PublicUrl,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Status,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssetStatus = `-- name: UpdateAssetStatus :one
update assets
set
  status = $1::asset_status,
  deleted_at = $2
where asset_id = $3
returning asset_id, filename, content_type, byte_size, storage_key, public_url, created_by, created_at, status, deleted_at
`

type UpdateAssetStatusParams struct {
	Status    AssetStatus
	DeletedAt pgtype.Timestamptz
	AssetID   pgtype.UUID
}

func (q *Queries) UpdateAssetStatus(ctx context.Context, arg UpdateAssetStatusParams) (Asset, error) {
	row := q.db.QueryRow(ctx, updateAssetStatus, arg.Status, arg.DeletedAt, arg.AssetID)
	var i Asset
	err := row.Scan(
		&i.AssetID,
		&i.Filename,
		&i.ContentType,
		&i.ByteSize,
		&i.StorageKey,
		&i.PublicUrl,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Status,
		&i.DeletedAt,
	)
	return i, err
}
