// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assets.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAssetByID = `-- name: GetAssetByID :one
select asset_id, filename, content_type, byte_size, storage_key, public_url, created_by, created_at
from assets
where asset_id = $1
`

func (q *Queries) GetAssetByID(ctx context.Context, assetID pgtype.UUID) (Asset, error) {
	row := q.db.QueryRow(ctx, getAssetByID, assetID)
	var i Asset
	err := row.Scan(
		&i.AssetID,
		&i.Filename,
		&i.ContentType,
		&i.ByteSize,
		&i.StorageKey,
		&i.PublicUrl,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listAssets = `-- name: ListAssets :many
select asset_id, filename, content_type, byte_size, storage_key, public_url, created_by, created_at
from assets
order by created_at desc
`

func (q *Queries) ListAssets(ctx context.Context) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.AssetID,
			&i.Filename,
			&i.ContentType,
			&i.ByteSize,
			&i.StorageKey,
			&i.PublicUrl,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
