// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_security.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLoginAttempt = `-- name: CreateLoginAttempt :one
insert into login_attempts (
  email,
  ip_hash,
  success,
  failure_reason
) values (
  $1,
  $2,
  $3,
  $4
)
returning attempt_id, email, ip_hash, success, failure_reason, created_at
`

type CreateLoginAttemptParams struct {
	Email         string
	IpHash        string
	Success       bool
	FailureReason pgtype.Text
}

func (q *Queries) CreateLoginAttempt(ctx context.Context, arg CreateLoginAttemptParams) (LoginAttempt, error) {
	row := q.db.QueryRow(ctx, createLoginAttempt,
		arg.Email,
		arg.IpHash,
		arg.Success,
		arg.FailureReason,
	)
	var i LoginAttempt
	err := row.Scan(
		&i.AttemptID,
		&i.Email,
		&i.IpHash,
		&i.Success,
		&i.FailureReason,
		&i.CreatedAt,
	)
	return i, err
}

const listRecentFailedLoginAttemptsByEmail = `-- name: ListRecentFailedLoginAttemptsByEmail :many
select created_at
from login_attempts
where success = false
  and created_at >= $1
  and email = $2
order by created_at desc
`

type ListRecentFailedLoginAttemptsByEmailParams struct {
	CreatedAt pgtype.Timestamptz
	Email     string
}

func (q *Queries) ListRecentFailedLoginAttemptsByEmail(ctx context.Context, arg ListRecentFailedLoginAttemptsByEmailParams) ([]pgtype.Timestamptz, error) {
	rows, err := q.db.Query(ctx, listRecentFailedLoginAttemptsByEmail, arg.CreatedAt, arg.Email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Timestamptz
	for rows.Next() {
		var created_at pgtype.Timestamptz
		if err := rows.Scan(&created_at); err != nil {
			return nil, err
		}
		items = append(items, created_at)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentFailedLoginAttemptsByIP = `-- name: ListRecentFailedLoginAttemptsByIP :many
select created_at
from login_attempts
where success = false
  and created_at >= $1
  and ip_hash = $2
order by created_at desc
`

type ListRecentFailedLoginAttemptsByIPParams struct {
	CreatedAt pgtype.Timestamptz
	IpHash    string
}

func (q *Queries) ListRecentFailedLoginAttemptsByIP(ctx context.Context, arg ListRecentFailedLoginAttemptsByIPParams) ([]pgtype.Timestamptz, error) {
	rows, err := q.db.Query(ctx, listRecentFailedLoginAttemptsByIP, arg.CreatedAt, arg.IpHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Timestamptz
	for rows.Next() {
		var created_at pgtype.Timestamptz
		if err := rows.Scan(&created_at); err != nil {
			return nil, err
		}
		items = append(items, created_at)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
