// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listApprovedCommentsByArticle = `-- name: ListApprovedCommentsByArticle :many
select
  comment_id,
  article_id,
  author_name,
  author_email,
  body,
  status,
  ip_hash,
  user_agent,
  created_at,
  reviewed_at
from comments
where article_id = $1 and status = 'approved'
order by created_at asc
`

func (q *Queries) ListApprovedCommentsByArticle(ctx context.Context, articleID pgtype.UUID) ([]Comment, error) {
	rows, err := q.db.Query(ctx, listApprovedCommentsByArticle, articleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.CommentID,
			&i.ArticleID,
			&i.AuthorName,
			&i.AuthorEmail,
			&i.Body,
			&i.Status,
			&i.IpHash,
			&i.UserAgent,
			&i.CreatedAt,
			&i.ReviewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingComments = `-- name: ListPendingComments :many
select
  comment_id,
  article_id,
  author_name,
  author_email,
  body,
  status,
  ip_hash,
  user_agent,
  created_at,
  reviewed_at
from comments
where status = 'pending'
order by created_at asc
`

func (q *Queries) ListPendingComments(ctx context.Context) ([]Comment, error) {
	rows, err := q.db.Query(ctx, listPendingComments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.CommentID,
			&i.ArticleID,
			&i.AuthorName,
			&i.AuthorEmail,
			&i.Body,
			&i.Status,
			&i.IpHash,
			&i.UserAgent,
			&i.CreatedAt,
			&i.ReviewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
