// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ArticleStatus string

const (
	ArticleStatusDraft     ArticleStatus = "draft"
	ArticleStatusPublished ArticleStatus = "published"
	ArticleStatusArchived  ArticleStatus = "archived"
)

func (e *ArticleStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ArticleStatus(s)
	case string:
		*e = ArticleStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ArticleStatus: %T", src)
	}
	return nil
}

type NullArticleStatus struct {
	ArticleStatus ArticleStatus
	Valid         bool // Valid is true if ArticleStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullArticleStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ArticleStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ArticleStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullArticleStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ArticleStatus), nil
}

type CommentStatus string

const (
	CommentStatusPending  CommentStatus = "pending"
	CommentStatusApproved CommentStatus = "approved"
	CommentStatusRejected CommentStatus = "rejected"
)

func (e *CommentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CommentStatus(s)
	case string:
		*e = CommentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CommentStatus: %T", src)
	}
	return nil
}

type NullCommentStatus struct {
	CommentStatus CommentStatus
	Valid         bool // Valid is true if CommentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCommentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CommentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CommentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCommentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CommentStatus), nil
}

type UserRole string

const (
	UserRoleAdmin  UserRole = "admin"
	UserRoleEditor UserRole = "editor"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Article struct {
	ArticleID     pgtype.UUID
	Slug          string
	Title         string
	Summary       string
	BodyMdx       string
	Status        ArticleStatus
	Tags          []string
	Featured      bool
	CoverImageUrl pgtype.Text
	PublishedAt   pgtype.Timestamptz
	AuthorID      pgtype.UUID
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Version       int32
	SearchVector  interface{}
}

type ArticleLog struct {
	ArticleID     pgtype.UUID
	Slug          string
	Title         string
	Summary       string
	BodyMdx       string
	Status        ArticleStatus
	Tags          []string
	Featured      bool
	CoverImageUrl pgtype.Text
	PublishedAt   pgtype.Timestamptz
	AuthorID      pgtype.UUID
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Version       int32
}

type ArticleViewDaily struct {
	ArticleID pgtype.UUID
	ViewDate  pgtype.Date
	Views     int32
}

type ArticleViewHistory struct {
	ArticleID  pgtype.UUID
	ViewDate   pgtype.Date
	Views      int32
	ArchivedAt pgtype.Timestamptz
}

type Asset struct {
	AssetID     pgtype.UUID
	Filename    string
	ContentType string
	ByteSize    int32
	StorageKey  string
	PublicUrl   pgtype.Text
	CreatedBy   pgtype.UUID
	CreatedAt   pgtype.Timestamptz
}

type Comment struct {
	CommentID   pgtype.UUID
	ArticleID   pgtype.UUID
	AuthorName  string
	AuthorEmail pgtype.Text
	Body        string
	Status      CommentStatus
	IpHash      string
	UserAgent   pgtype.Text
	CreatedAt   pgtype.Timestamptz
	ReviewedAt  pgtype.Timestamptz
}

type DownloadEvent struct {
	EventID   pgtype.UUID
	AssetID   pgtype.UUID
	IpHash    string
	UserAgent pgtype.Text
	CreatedAt pgtype.Timestamptz
}

type SiteViewDaily struct {
	ViewDate pgtype.Date
	Views    int32
}

type SiteViewHistory struct {
	ViewDate   pgtype.Date
	Views      int32
	ArchivedAt pgtype.Timestamptz
}

type User struct {
	UserID       pgtype.UUID
	Email        string
	Name         string
	PasswordHash string
	Role         UserRole
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
