// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const searchPublishedArticles = `-- name: SearchPublishedArticles :many
select
  article_id,
  slug,
  title,
  summary,
  published_at
from articles
where status = 'published'
  and search_vector @@ plainto_tsquery('simple', $1)
order by ts_rank(search_vector, plainto_tsquery('simple', $1)) desc, published_at desc
`

type SearchPublishedArticlesRow struct {
	ArticleID   pgtype.UUID
	Slug        string
	Title       string
	Summary     string
	PublishedAt pgtype.Timestamptz
}

func (q *Queries) SearchPublishedArticles(ctx context.Context, query string) ([]SearchPublishedArticlesRow, error) {
	rows, err := q.db.Query(ctx, searchPublishedArticles, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPublishedArticlesRow
	for rows.Next() {
		var i SearchPublishedArticlesRow
		if err := rows.Scan(
			&i.ArticleID,
			&i.Slug,
			&i.Title,
			&i.Summary,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
